version: '3'
services:
  # Define the MySQL service
  mysql_container:
    image: mysql:8.0
    restart: always
#    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_container
    environment:
     MYSQL_DATABASE: 'world'
     MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - /home/kasra/codebase/world.sql:/world.sql
      - /home/kasra/codebase/mysql_entrypoint.sh:/mysql_entrypoint.sh
    networks:
      - mynetwork
    entrypoint: /mysql_entrypoint.sh

  # Django application service
  django_container:
    image: simple_django:1.0.6
    build:
      context: .
    container_name: simple-django
    command: >
     sh -c "
     pip install --upgrade pip &&
     python -m venv venv &&
     /app/venv/bin/pip install -r requirements.txt &&
     /app/venv/bin/python manage.py makemigrations &&
     /app/venv/bin/python manage.py migrate &&
     /app/venv/bin/python manage.py rebuild_index &&
     /app/venv/bin/python manage.py runserver 0:8001"

    volumes:
      - /home/kasra/codebase/entrypoint.sh:/app/entrypoint.sh
    depends_on:
      - mysql_container
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    volumes:
      - ./:/app  # Mount your Django app code

networks:
  mynetwork:

volumes:
  db_data:
